---
- name: Make sur tar and git are installed
  package:
    name:
      - tar
      - git
    state: latest

- name: Download and install go release
  unarchive:
    src: "{{ golang_release_download_url }}"
    dest: /usr/local/
    remote_src: yes
